try new install_neovim;

diff --git a/install_neovim b/install_neovim
--- a/install_neovim
+++ b/install_neovim
@@ -1,8 +1,21 @@
 #!/bin/sh
 
-# Stable build
-URL="https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz"
+# Detect architecture and set proper URL
+ARCH=$(uname -m)
+BASE_URL="https://github.com/neovim/neovim/releases/download/stable"
 
-curl -L ${URL} > neovim_tmp.tar.gz;
-tar -xf neovim_tmp.tar.gz;
-rm -rf neovim_tmp.tar.gz;
+case "$ARCH" in
+    x86_64)  FILE="nvim-linux-x86_64.tar.gz" ;;
+    aarch64) FILE="nvim-linux-arm64.tar.gz" ;;
+    *)
+        echo "Unsupported architecture: $ARCH"
+        exit 1
+        ;;
+esac
+
+URL="$BASE_URL/$FILE"
+
+# Download, extract, clean up
+curl -L "$URL" -o neovim_tmp.tar.gz
+tar -xf neovim_tmp.tar.gz
+rm -f neovim_tmp.tar.gz
